#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': u'0.11',
 'build_date': '2009-10-23 00:13:47 +0200',
 'clean': None,
 'date': '2009-10-23 00:13:31 +0200',
 'revision_id': 'soren@canonical.com-20091022221331-knxf3bpaj1q9kf6i',
 'revno': 353}

revisions = {}

file_revisions = {}



if __name__ == '__main__':
    print 'revision: %(revno)d' % version_info
    print 'nick: %(branch_nick)s' % version_info
    print 'revision id: %(revision_id)s' % version_info
